# SITE CONFIGURATION
baseurl: ""
url: "https://www.r4podcast.com"

# THEME-SPECIFIC CONFIGURATION
title: "The R4 Running Podcast"                                   # site's title
description: "Conor Hoekstra & YüBaí Liu"      # used by search engines
avatar: assets/img/pexels/funrun.png              # Empty for no avatar in navbar
favicon: assets/img/pexels/funrun.png             # Icon displayed in the tab

# Header and footer text
header_text: "The R4 Running Podcast"  # Change Blog header text
header_feature_image: assets/img/pexels/funrun_header.png
footer_text: ""

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
